accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

home/urls.py
# home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('company/', views.company, name='company'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mysite/', include('mysite.urls')),
    path('', include('home.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('evento/', include('evento.urls')),
]

#미디어 파일 서빙
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="csrf-token" content="{{ csrf_token }}">
    <title>세상의 모든 야옹이가 행복해지는 그 날 까지!</title>
   {% load static %}
   <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'mainpage.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'JS/points.js' %}"></script>
</head>

<body>
<div class="header-container">
 <header>
    <img src="{% static 'images/메인.jpg' %}" alt="Company Logo" class="company-logo"/>
  </header>

<div class="language-selector">
        <button class="language-button" data-language="ja">日本語</button>
        <button class="language-button" data-language="en">English</button>
        <button class="language-button" data-language="zh">中文</button>
     </div>
</div>

  {% include "navbar.html" %}
  {% block content %}
  {% endblock %}

  {% include "footer.html" %}
</body>
</html>

templates/footer.html
<footer class="py-5 main-footer">
    <div class="call-cs">
        <p class="cscall">Customer Center</p>
        <p class="call-number">전화번호: 010-8665-1031</p>
        <p class="mail">이메일: ziahime0518@gmail.com</p>
        <p class="work-time">업무 시간: 09:00~19:00</p>
        <p class="lunch">점심 시간: 13:00~14:00</p>
    </div>

    <div class="money">
        <p class="bank">Bank Info</p>
        <p class="bank-num">카카오뱅크 1111-22-3333-444</p>
        <p class="my-money">예금주: 우*아</p>
    </div>

    <div class="return">
        <p class="re-re">Return / Exchange</p>
        <p class="ban-pum">반품주소: 서울시 강서구 화곡동</p>
    </div>

    <div class="info">
        <p class="company-info">Company Info</p>
        <p class="ban-pum">본 사이트는 포트폴리오용 홈페이지로<br> 실제 구매가 불가능하며</p>
        <p class="ban-pum2">수익창출을 일절 하지 않음을 알립니다</p><br>
    </div>
</footer>

templates/navbar.html

<div id="searchBar">
    <form action="#" method="post">
        <input type="text" id="searchInput" name="pname" placeholder="야옹이가 세계를 구한다!">
        <button type="submit" id="searchButton">검색! 🔍</button>
    </form>
</div>


<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="/">💜 메인 페이지</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/company/">어바웃-야세지</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/mysite/">구독상품</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="/mysite/recomm/">추천/혜택</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/commu/">라운지</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link" href="/evento/">이벤트</a>
                </li>
               {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }} (로그아웃)</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
    {% endif %}
    </ul>
        </ul>
        </div>
    </div>
</nav>